---
editor: 
  markdown: 
    wrap: 72
---

# Introduction

## Overview and motivations

This project will analyze the factors influencing Criminality in France.
We chose this subject because we are both french and criminality
consistently ranks as one of the most important priority for the French
population. In our study, we wanted to focus on the social and economic
factors contributing to this issue. France is often regarded as one of
the major world powers, and yet, it is clear that similarly to the rest
of the world, there are increasing safety concerns regarding crime. This
subject has also made it's way into everyday discussions as it proves to
be a polarizing topic. In the last thirty years, Politicians have often
promised to tackle crime through several means, and as the population
wants more to be done against it, the government has often made it one
of their top priority.

In recent times, there has been a noticeable rise in criminal activities
across France. Regions such as "Seine Saint Denis" in the Paris area.
has seen emboldened criminals committing crimes in broad daylight,
contributing to a perception of increased chaos. Similar concerns have
surfaced in cities like Marseille. Additionally, it's worth noting that
the prison population has reached an all-time high in July 2023. But
what are the reasons for increased criminality?

The goal of our research is to synthesize the main reasons behind
criminality. Medias have often presented various reasons to explain
crime, our research will look at those hints and see if they may have
any statistical significance. It should be noted that data regarding
"Ethnic origin" is not available, this variable is singled out
by some as one of the driver of criminality and unlike in the United
States, France has outlawed any form of statistics on this subject. As
such, we will mostly focus on socio-economics drivers behind crime.

Overall, France is facing substantial socio-economics issues, unemployment,
poverty, retirement age, and a decline in the education level. Our project explores
the link between socio-economic factors and criminality rates.
Establishing such a link would give a new outlook on crime and its
causes. Additionally we would like to know whether, this data could be
used by the government to address public safety. In this project we will
get answers regarding the core human drivers that push humans to commit
crimes and how their socio-economic environment or educational path may
impact their ability to commit crime.

## Associated papers

<https://www.institutpourlajustice.org/content/2017/12/Pauvreté-et-délinquance.pdf>

<https://www.bfmtv.com/politique/sondages/le-pouvoir-d-achat-reste-de-loin-la-priorite-ndeg1-des-francais-devant-la-securite-en-forte-hausse_AN-202308300557.html>

<https://www.leparisien.fr/politique/emmanuel-macron-donnera-ce-lundi-une-interview-sur-le-theme-de-la-securite-au-jt-de-france-3-01-10-2023-GYXJJQBWAFDEZBIX2DY3AJ3QJM.php>

## Research questions

The purpose of this study is to evaluate the impact of different
socioeconomic factors on criminality in France. We are using for that a
french government database which divide crimes in 14 categories. In our
regression analysis, we decided to focus on the five most common types
of crime:

1.  Assault and Battery

2.  Burglaries

3.  Intentional damage and destructions

4.  Drug use

5.  Theft without violence

We will consider the following macroeconomic variables:

-   Poverty rate,
-   Unemployment rate
-   School indicators(Success rate at an exam/Share of adults without a
    dimploma)
-   Density of Population
-   Results of previous presidential election.
-   Immigration

These are the following question we will focus on:

-   Can the criminality rate in France be explained using the
    unemployment rate?
-   Can the criminality rate in France be explained using the poverty
    rate?
-   Can the criminality rate in France be explained using education
    indicators ?
-   Can the density of population in territories explain criminality?
-   Can the immigration rate explain criminality?
-   Can the previous presidential results in territories have an impact
    on criminality?
-   Is there a correlation between these mentioned variables?